# Don't change this! Version used to track needed updates.
version = 0

[gamma]
toggleValue = 1500.0
defaultValue = 100.0
sliderInterval = 1.0
transition = true
transitionTime = 30

[fakeNightVision]
enabled = false
scale = 100.0
transition = true
transitionTime = 20
fog = true

[removeBlindness]
enabled = false
transition = false
transitionTime = 20

[removeDarkness]
enabled = true
transition = false
transitionTime = 20